### ISSUE TITLE
Window resize fix

### ISSUE THREAD

**Issue by Rigo-m** [jsnanigans/vue-parallax-js#9] opened 2018-01-22 10:25 UTC
When the window gets resized, the parallax doesn't adjust to window changes.

**Comment by jsnanigans** [comment] 2018-01-22 12:32
Could you describe your issue in some more detail? maybe add a example?

**Comment by Rigo-m** [comment] 2018-01-23 15:01
I'll try to add an example as soon as I have some time.
By looking at the code, I can see that there are a lot of reference to window height, but these references doesn't get updated if window height get resized, right?

Besides that, I am struggling to find a way to have parallax triggered only when the window gets past him (shouldn't be parallaxed until the window is actually scrolling after, or else every design one would work on would be distorted too much by parallax), but maybe this is another issue, hit me back if I need to be more clear/I can be of some help, thanks

**Comment by jsnanigans** [comment] 2018-01-23 15:09
The elements get repositioned when the page resizes here:
https://github.com/jsnanigans/vue-parallax-js/blob/master/src/vue-parallax-js.js#L85-L87

Do you mean like "if element is in view port, then animate"?
that would break this kind of parallax, since it animates elements in the whole window, and not just in some container, like a background of a section, i explained this in depth here:
https://github.com/jsnanigans/vue-parallax-js/issues/6#issuecomment-344308644
but if you have a solution for this, that would be awesome

**Comment by Rigo-m** [comment] 2018-01-23 15:46
Yeah now I saw it.

So, as far as the element in viewport, my educated guess would be that an Intersection obsever with the possibility to change root margin would suffice.

E.g.: If I have a text in a full height (100vh) section is placed 50px from the top of the section, then I would like to have it parallaxed when this section is visible and also I would like to parallax it after the section is going out of the viewport. So, the best thing to do here is to observe the intersection of the element with the viewport when it's starting to go out of it and parallax it as it is going out.

I don't know if I'm being very clear here, I'm doing my best :smile:

**Comment by Rigo-m** [comment] 2018-01-23 16:14
Or maybe we could check at initialization how far is the element from the top of the window and detract that value (plus or minus a parametric offset) from the scrollY value?

**Comment by jsnanigans** [comment] 2018-01-23 19:22
I think we could add that as a optional feature.
If I understand you correctly, I would solve it like this.

Setup: the section is 100vh heigh and is 2000px offset from the top of the document, it is set to parallax downward at 0.5 speed.
Only if the bottom of the screen is below 2000px then the section is animated.

The problem is that this will only work with parallax values from `>= 0 && < 1` or in other words downwards and slower than the scroll speed

**Comment by Rigo-m** [comment] 2018-01-25 15:04
If the bottom of the screen is below 2000px then it works with 0 < v < 1 parallax values, if we start animating when the section hit the top of the page then its -1 < v < 0, so like this it could work either one or the other direction, am I wrong?

We could pass an additional parameter like this, maybe:
`v-parallax="{ speed: 0.2, offset: el }"`
and if the speed is positive, we work by reading when the element's top side hits the bottom of the page, if the speed is negative we start animating parallax when the element's top side hits the top of the page (and goes outward)

Would you like this feature? Do you find it feasible to insert it inside the project? May i help you with it?

**Comment by eybarta** [comment] 2018-05-01 18:35
I was just going to open an issue on this matter where parallaxed items aren't being updated on window resize.. I fixed it in the code by adding an update method, will open a PR

**Comment by jsnanigans** [comment] 2018-05-02 09:59
fixed in `vue-parallax-js@0.1.2` thanks to @eybarta for the PR

**Closed as completed by jsnanigans** 2018-05-02 09:59 UTC
Labels: enhancement, help wanted
